name: universal_miniprogram_api
description: The MPFlutter universal miniprogram api.
publish_to: none
version: 0.0.4
homepage: /

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter: ">=0.11.0"
  mpcore: ">=0.11.0"